import { supabase } from '../lib/supabase';
import { subDays, format } from 'date-fns';

export async function seedClaimsData() {
    const claims = [
        {
            claim_id: 'CLM-2024-001',
            total_claim_charge_amount: 15000.00,
            facility_type_code: '011',
            facility_type_desc: 'Hospital Inpatient',
            facility_code_qualifier: 'B',
            facility_code_qualifier_desc: 'Place of Service',
            claim_frequency_type_code: '1',
            claim_frequency_type_desc: 'Original',
            service_date_start: format(subDays(new Date(), 30), 'yyyy-MM-dd'),
            service_date_end: format(subDays(new Date(), 25), 'yyyy-MM-dd'),
            admission_type_code: '1',
            admission_type_desc: 'Emergency',
            admission_source_code: '1',
            admission_source_desc: 'Physician Referral',
            patient_status_code: '01',
            patient_status_desc: 'Discharged to Home',
            claim_filing_indicator_code: 'CI',
            claim_filing_indicator_desc: 'Commercial Insurance',
            assignment_code: 'A',
            assignment_desc: 'Assigned',
            benefits_assignment: 'Y',
            benefits_assignment_desc: 'Yes',
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString()
        },
        {
            claim_id: 'CLM-2024-002',
            total_claim_charge_amount: 5000.00,
            facility_type_code: '013',
            facility_type_desc: 'Hospital Outpatient',
            facility_code_qualifier: 'B',
            facility_code_qualifier_desc: 'Place of Service',
            claim_frequency_type_code: '1',
            claim_frequency_type_desc: 'Original',
            service_date_start: format(subDays(new Date(), 15), 'yyyy-MM-dd'),
            service_date_end: format(subDays(new Date(), 15), 'yyyy-MM-dd'),
            admission_type_code: '2',
            admission_type_desc: 'Urgent',
            admission_source_code: '2',
            admission_source_desc: 'Clinic Referral',
            patient_status_code: '01',
            patient_status_desc: 'Discharged to Home',
            claim_filing_indicator_code: 'MB',
            claim_filing_indicator_desc: 'Medicare Part A',
            assignment_code: 'A',
            assignment_desc: 'Assigned',
            benefits_assignment: 'Y',
            benefits_assignment_desc: 'Yes',
            created_at: subDays(new Date(), 10).toISOString(),
            updated_at: subDays(new Date(), 10).toISOString()
        },
        {
            claim_id: 'CLM-2024-003',
            total_claim_charge_amount: 45000.00,
            facility_type_code: '011',
            facility_type_desc: 'Hospital Inpatient',
            facility_code_qualifier: 'B',
            facility_code_qualifier_desc: 'Place of Service',
            claim_frequency_type_code: '7',
            claim_frequency_type_desc: 'Replacement',
            service_date_start: format(subDays(new Date(), 60), 'yyyy-MM-dd'),
            service_date_end: format(subDays(new Date(), 50), 'yyyy-MM-dd'),
            admission_type_code: '1',
            admission_type_desc: 'Emergency',
            admission_source_code: '7',
            admission_source_desc: 'Emergency Room',
            patient_status_code: '03',
            patient_status_desc: 'Discharged/Transferred to SNF',
            claim_filing_indicator_code: 'MC',
            claim_filing_indicator_desc: 'Medicaid',
            assignment_code: 'A',
            assignment_desc: 'Assigned',
            benefits_assignment: 'Y',
            benefits_assignment_desc: 'Yes',
            created_at: subDays(new Date(), 45).toISOString(),
            updated_at: subDays(new Date(), 5).toISOString()
        },
        {
            claim_id: 'CLM-2024-004',
            total_claim_charge_amount: 2500.00,
            facility_type_code: '083',
            facility_type_desc: 'Ambulatory Surgical Center',
            facility_code_qualifier: 'B',
            facility_code_qualifier_desc: 'Place of Service',
            claim_frequency_type_code: '1',
            claim_frequency_type_desc: 'Original',
            service_date_start: format(subDays(new Date(), 5), 'yyyy-MM-dd'),
            service_date_end: format(subDays(new Date(), 5), 'yyyy-MM-dd'),
            admission_type_code: '3',
            admission_type_desc: 'Elective',
            admission_source_code: '1',
            admission_source_desc: 'Physician Referral',
            patient_status_code: '01',
            patient_status_desc: 'Discharged to Home',
            claim_filing_indicator_code: 'WC',
            claim_filing_indicator_desc: 'Workers Compensation',
            assignment_code: 'A',
            assignment_desc: 'Assigned',
            benefits_assignment: 'Y',
            benefits_assignment_desc: 'Yes',
            created_at: subDays(new Date(), 2).toISOString(),
            updated_at: subDays(new Date(), 2).toISOString()
        },
        {
            claim_id: 'CLM-2024-005',
            total_claim_charge_amount: 12000.00,
            facility_type_code: '011',
            facility_type_desc: 'Hospital Inpatient',
            facility_code_qualifier: 'B',
            facility_code_qualifier_desc: 'Place of Service',
            claim_frequency_type_code: '1',
            claim_frequency_type_desc: 'Original',
            service_date_start: format(subDays(new Date(), 90), 'yyyy-MM-dd'),
            service_date_end: format(subDays(new Date(), 85), 'yyyy-MM-dd'),
            admission_type_code: '1',
            admission_type_desc: 'Emergency',
            admission_source_code: '7',
            admission_source_desc: 'Emergency Room',
            patient_status_code: '01',
            patient_status_desc: 'Discharged to Home',
            claim_filing_indicator_code: 'CI',
            claim_filing_indicator_desc: 'Commercial Insurance',
            assignment_code: 'A',
            assignment_desc: 'Assigned',
            benefits_assignment: 'Y',
            benefits_assignment_desc: 'Yes',
            created_at: subDays(new Date(), 80).toISOString(),
            updated_at: subDays(new Date(), 80).toISOString()
        }
    ];

    const { error } = await supabase
        .from('healthcare_claims')
        .insert(claims);

    if (error) {
        console.error('Error seeding data:', error);
        throw error;
    }
}
