# -*- coding: utf-8 -*-
"""Read_EDI_if_else_10152024_060625_v1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JBR9qT76kZuKcPeBkbOuHnqaT4IhtMMt

## import zipfile
import os
import json
import pandas as pd
#import shutils
from itertools import chain
"""

folder_path = '/Users/kushalvelapakam/Desktop/Marb/Qurom/Test/Test1/'

def validate_segment_length(segments, expected_length):
    """ Ensures that the segment has at least the expected number of elements. """
    return [segments[i] if i < len(segments) else "" for i in range(expected_length)]

def parse_edi_segments(folder_path):
    for file_name in os.listdir(folder_path):
        #filename = file_name
        segment_data = []
        if file_name.endswith(".TXT"):  # Assuming EDI files have .txt extension
            file_path = os.path.join(folder_path, file_name)
            filename = file_name
            #print(f"Processing file: {file_name}")
            with open(file_path, 'r') as file:
                lines = file.read().split("~")
                edi_data = {"SegmentDelimiter": "~", "DataElementDelimiter": "*"}#, "ISA": {}, "Groups": []}
                for line in lines:
                    segments = line.strip().split('*')
                    segment_data.append(segments)
            #print(segment_data)
    return filename, segment_data

edi = parse_edi_segments(folder_path)

"""# Global Variables"""

filename = edi[0]

"""# Get Claim Blocks Begins with HL Subscriber segment, HL and index 3 = 22"""

segment_identifier= 'HL'
subcriber_record_identifier= '22'

def get_claim_blocks():


    claim_blocks = []
    current_claim = []

    for clm_blocks_segs in edi[1]:
        #print(clm_blocks_segs)
        seg_identifier = clm_blocks_segs[0]
        if seg_identifier == segment_identifier and len(clm_blocks_segs) >= 4 and\
            clm_blocks_segs[3] == subcriber_record_identifier:
            if current_claim:
            #look for HL segments with 22 as it represents the subscriber and begining of the segment

                #if current claim is true or populated append it to the claim block
                #code only enters this if condition if current_claim is true, when current claim is true
                #the data in current_claim is contains all the data begining  HL segment with 22 and the entire
                #block of segments until the code finds the next HL 22 segment
                #claim_blocks only appends the claim block (entire claim block from HL 22 to end of the claim)
                claim_blocks.append(current_claim)

                #once the claim is appended, set the current_claim to empty list
                current_claim = []

                #HL segment with 22 will be passed to the segment below and set the current_claim to true
            current_claim.append(clm_blocks_segs)

        elif current_claim:
            current_claim.append(clm_blocks_segs)

    if current_claim:
        claim_blocks.append(current_claim)

    return claim_blocks

"""# Use Claim Block to get specific segments within claim block segment"""



def get_segment_claimid(segment_id):

    final_segment = []
    count_seg_claim_blocks = 0
    for clm_seg_blocks in get_claim_blocks():
        #claimid = 'No Claim'
        #match_found = False
        for clm_seg_ent in clm_seg_blocks:
            if isinstance(clm_seg_ent, list) and len(clm_seg_ent) >= 2:
                if clm_seg_ent[0] == 'CLM':
                    claimid = clm_seg_ent[1]
                    break

        for clm_seg_ent in clm_seg_blocks:
            if isinstance(clm_seg_ent, list) and clm_seg_ent[0] == segment_id:
                count_seg_claim_blocks += clm_seg_ent.count(segment_id)
                final_segment.append([clm_seg_ent, claimid])
                #match_found = True
                #break

    return final_segment, count_seg_claim_blocks

"""# Use Claim Block to get specific segments, entityid within claim block segment"""

def get_segment_entity_id_claimid(segment_id, entity_id):

    final_segment = []
    clm_seg_entityid_blocks = 0
    for clm_seg_blocks in get_claim_blocks():
        #claimid = 'No Claim'
        #match_found = False
        for clm_seg_ent in clm_seg_blocks:
            if isinstance(clm_seg_ent, list) and len(clm_seg_ent) >= 2:
                if clm_seg_ent[0] == 'CLM':
                    claimid = clm_seg_ent[1]
                    break

        for clm_seg_ent in clm_seg_blocks:
            if isinstance(clm_seg_ent, list) and clm_seg_ent[0] == segment_id and clm_seg_ent[1] == entity_id :
                clm_seg_entityid_blocks += clm_seg_ent.count(segment_id)
                final_segment.append([clm_seg_ent, claimid])
                #match_found = True
                #break

    return final_segment, clm_seg_entityid_blocks

"""# Use Claim Block to get Claimid, Claim Line, specific segments within 2400 Loop. Line Level Data"""

def get_claimid_n_line_use_line_segmentid(line_segment_id):

    line_records = []
    clm_line_blocks = 0
    for clm_line_seg_blocks in get_claim_blocks():
        claimid = None
        claim_line = None
        for clm_line_seg in clm_line_seg_blocks:
            #print(clm_seg_ent)
            if clm_line_seg[0] == 'CLM':
                claimid = clm_line_seg[1]
            elif clm_line_seg[0] == 'LX':
                claim_line = clm_line_seg[1]
                #print(current_lx)
            elif clm_line_seg[0] == line_segment_id and claimid and claim_line:
                clm_line_blocks += clm_line_seg.count(clm_line_seg[0])
                line_records.append([clm_line_seg, [claimid, claim_line]])

    return line_records,clm_line_blocks

"""# Get Claimid and Claim Line between 2 segments, pass initial segmentid , final segmentid and required line segmentid"""

def get_claimid_n_line_btwn_2_segs_claim_line_block(begin_segmentid, end_segmentid, req_line_segmentid):

    line_records = []
    count_seg_claim_line_blocks = 0

    for clm_line_blck in get_claim_blocks():

        #print(isinstance(clm_line_blck, list))
        #print(clm_line_blck)
        in_claim_line_hdr = False
        for clm_hdr_line_lvl_seg in clm_line_blck:
            #print(isinstance(clm_hdr_line_lvl_seg, list))
            if not isinstance(clm_hdr_line_lvl_seg, list) or not clm_hdr_line_lvl_seg:
                #print(clm_hdr_line_lvl_seg)
                continue
            if clm_hdr_line_lvl_seg[0] == "CLM":
                claimid = clm_hdr_line_lvl_seg[1]
                #print(claimid)
            elif clm_hdr_line_lvl_seg[0] == 'LX':
                claim_line = clm_hdr_line_lvl_seg[1]
                #print(claimid,claim_line)
            elif clm_hdr_line_lvl_seg[0] == begin_segmentid:
                in_claim_line_hdr = True
            elif clm_hdr_line_lvl_seg[0] == end_segmentid:
                in_claim_line_hdr = False
                break
            elif in_claim_line_hdr and clm_hdr_line_lvl_seg[0] == req_line_segmentid:
                count_seg_claim_line_blocks += clm_hdr_line_lvl_seg.count(req_line_segmentid)
                    #get_req_segments.append([clm_hdr_line_lvl_seg,claimid] )
                line_records.append([clm_hdr_line_lvl_seg, [claimid, claim_line]])

    return line_records,count_seg_claim_line_blocks

"""# Get 2 related segments example SBR, P and NM1, PR. Also get Claimid and Claim Line"""

def get_claimid_n_line_for_related_segmets(segmentid, entityid,rltd_segmentid,rltd_entityid):
    line_records = []
    count_seg_claim_line_blocks = 0

    for clm_line_block in get_claim_blocks():
        claimid = ''
        claim_line = ''
        begin_seg_elements = None
        end_seg_elements = None
        in_claim_line_hdr = False

        for clm_hdr_line_lvl_seg in clm_line_block:
            if not isinstance(clm_hdr_line_lvl_seg, list) or not clm_hdr_line_lvl_seg:
                continue

            seg_id = clm_hdr_line_lvl_seg[0]

            if seg_id == "CLM" and len(clm_hdr_line_lvl_seg) > 1:
                claimid = clm_hdr_line_lvl_seg[1]

            elif seg_id == "LX" and len(clm_hdr_line_lvl_seg) > 1:
                claim_line = clm_hdr_line_lvl_seg[1]

            elif seg_id == segmentid and clm_hdr_line_lvl_seg[1] == entityid:
                begin_seg_elements = clm_hdr_line_lvl_seg
                in_claim_line_hdr = True

            elif seg_id == rltd_segmentid and clm_hdr_line_lvl_seg[1] == rltd_entityid and in_claim_line_hdr:
                end_seg_elements = clm_hdr_line_lvl_seg
                in_claim_line_hdr = False  # We found the end of this pair

        # Append only if all required segments are present
        if begin_seg_elements and end_seg_elements and claimid and claim_line and len(begin_seg_elements) >= 10:
            count_seg_claim_line_blocks += 1
            line_records.append([begin_seg_elements,end_seg_elements,[claimid, claim_line] ])
    return line_records, count_seg_claim_line_blocks

"""# Use Claim Block to get specific segments between 2 segments within the claim block segment"""

def get_segs_btwn_2_segs_claim_block(begin_segmentid, end_segmentid, req_segmentid):

    all_req_seg = []
    count_seg_claim_blocks = 0
    for clm_blck in get_claim_blocks():
        #print(b)
        in_claim_hdr = False
        #get_req_segments = []
        for clm_hdr_line_lvl_seg in clm_blck:
            if not isinstance(clm_hdr_line_lvl_seg, list) or not clm_hdr_line_lvl_seg:
                    continue
            if clm_hdr_line_lvl_seg[0] == "CLM":
                claimid = clm_hdr_line_lvl_seg[1]
            if clm_hdr_line_lvl_seg[0] == begin_segmentid:
                in_claim_hdr = True
            elif clm_hdr_line_lvl_seg[0] == end_segmentid:
                in_claim_hdr = False
                break
            elif in_claim_hdr and clm_hdr_line_lvl_seg[0] == req_segmentid:
                count_seg_claim_blocks += clm_hdr_line_lvl_seg.count(req_segmentid)
                #get_req_segments.append([clm_hdr_line_lvl_seg,claimid] )
                all_req_seg.append([clm_hdr_line_lvl_seg,claimid] )


        #all_req_seg.append(get_req_segments)


    return all_req_seg, count_seg_claim_blocks

"""# Function to get segment details in a list using segment id"""

def get_segment(segment_id):
    #def_segment = next((segment for segment in edi[1] if segment[0] == segment_id), None)
    def_segment = [segment for segment in edi[1] if segment[0] == segment_id]

    return def_segment

"""# Function to get segment details in a list using segment id and entityid"""

def get_segment_entityid(segment_id, entity_id):
    #def_segment = next((segment for segment in edi[1] if segment[0] == segment_id and segment[1] == entity_id), None)
    def_segment = [row for row in edi[1] if row[0] == segment_id and row[1] == entity_id]
    if isinstance(def_segment, list) and len(def_segment) == 1 and isinstance(def_segment[0], list):
        return def_segment[0]
    return def_segment

    #if any(isinstance(i, list) for i in def_segment) is True:
        #def_segment = list(chain.from_iterable(def_segment))
    #else:
        #def_segment = def_segment
    #return def_segment

"""# Function to count no of segments present in file, pass segment id (ISA, BHT etc..)"""

def count_segmnt_pass_segmentid(segment_id):
    count_seg = 0
    for seg_count in edi[1]:
        count_seg += seg_count.count(segment_id)

    return count_seg

"""# Function to count no of segments present in file, pass segment id and entity identifier"""

def count_segmnt_pass_segment_and_entity_id(segment_id, entity_id):
    count_segment_ent_id = 0
    for segment_ent_id in edi[1]:
            if segment_id in segment_ent_id:
                try:
                    index_seg_ent_id = segment_ent_id.index(segment_id)
                    if index_seg_ent_id + 1 < len(segment_ent_id) and segment_ent_id[index_seg_ent_id + 1] == entity_id:
                        #print(hl_1_seg)
                        count_segment_ent_id += 1
                except ValueError:
                    continue
    return count_segment_ent_id

"""# Get N4 adress for Specific Segment and Entityid"""

def get_segment_entityid_address(segment_id, entity_id, sub_segment_id):
    count_n4 = 0
    n4_records = []
    n4 = False

    for sub_seg in edi[1]:
        if sub_seg[0] == segment_id:
            if sub_seg[1] == entity_id:
                n4 = True
            else:
                n4 = False
        elif n4 and sub_seg[0] == sub_segment_id and len(sub_seg) >= 4:
            count_n4 += 1
            #n4_data = {"City": sub_seg[1],"State": sub_seg[2],"PostalCode": sub_seg[3]}
            n4_records.append([sub_seg[1], sub_seg[2], sub_seg[3]])
            n4 = False
    #print(n4_records)
    return n4_records, count_n4

"""# Get immediate next segment, pass segment id and the subsequent segment id"""

def get_subsequent_segment(segment_id, subsequent_seg_id):
    next_seg = []
    immediate_next_seg_count = 0
    raw_edi = edi[1]
    for index_x, next_seg_edi in enumerate(raw_edi):
        if isinstance(next_seg_edi, list) and len(next_seg_edi) > 0 and next_seg_edi[0] == segment_id:
            get_claimid = next_seg_edi[1]
            #print(get_claimid)
            if index_x + 1 < len(raw_edi):
                next_segment = raw_edi[index_x + 1]
                if isinstance(next_segment, list) and next_segment[0] == subsequent_seg_id:
                    immediate_next_seg_count += next_segment.count(subsequent_seg_id)
                    next_seg.append([next_segment,get_claimid ] )
    return next_seg, immediate_next_seg_count

"""# Error Message"""

def error_message_segmentid(df, segment_id):
    error_message = segment_id + " segment not found or has missing elements"

    if df.empty:
        df = pd.DataFrame({'file_name': [filename], 'error_message': [error_message]})
    else:
        if 'file_name' not in df.columns:
            df.insert(0, 'file_name', filename)
        else:
            df['file_name'] = filename

        if 'error_message' not in df.columns:
            df.insert(1, 'error_message', error_message)
        else:
            df['error_message'] = error_message

    print(segment_id, "segment not found or has missing elements.")
    return df

def error_message_segmentid_entityid(df, segment_id, entity_id):

    error_message = segment_id + '_' + entity_id +  " segment not found or has missing elements"

    if df.empty:
        df = pd.DataFrame({'file_name': [filename], 'error_message': [error_message]})
    else:
        if 'file_name' not in df.columns:
            df.insert(0, 'file_name', filename)
        else:
            df['file_name'] = file_name

        if 'error_message' not in df.columns:
            df.insert(1, 'error_message', error_message)
        else:
            df['error_message'] = error_message

    print(segment_id  + '_' + entity_id +  " segment and entity id not found or has missing elements.")
    return df

def insert_additional_cols_df(df, count_segs):
        df.insert(0, 'file_name', filename)
        df.insert(0, 'seg_count', count_segs)
        return df

facilitytypecode_mapping_dict = {
'11':'Office Physicians office',
'12': 'HomeServices provided at the patients home',
'13': 'Critical Access Hospital',
'14': 'Skilled Nursing Facility',
'18': 'Psychiatric Hospital',
'21': 'Inpatient Hospital Services',
'22': 'Outpatient Hospital',
'23': 'Emergency Room Services',
'24': 'Ambulatory Surgical Center Outpatient',
'31': 'Skilled Nursing Facility',
'32': 'Nursing Facility',
'41': 'Ambulance Land Ground transportation medical emergencies',
'42': 'Ambulance Air or water ambulance transport',
'51': 'Psychiatric inpatient care',
'61': 'Comprehensive Inpatient Rehabilitation Facility',
'71': 'State or Local Public Health Clinic',
'85': 'Critical Access Hospital'}


facilitycodequalifier_mapping_dict = {
'A':'Ambulatory Care Center',
'B':'Inpatient Facility',
'C':'Outpatient Clinic',
'D':'Diagnostic Testing Center',
'E':'Emergency Facility',
'F':'Specialty Clinic',
'G':'Home Health Care'}


frequencytypecode_mapping_dict = {
'1':'Original Claim',
'7':'Corrected Claim',
'8':'Void Claim',
'5':'Late Charge Claim',
'6':'Adjusted Claim'}

planparticipationCode_mapping_dict = {
    'A': 'Assigned, Required when the provider accepts|does not assignment and|or has a participation agreement with the payer',
    'B': 'Assigned, Assignment Accepted on Clinical Lab Services Only',
    'C': 'Not Assigned'}

hl_mapping_dict = {
        '20': 'Billing Provider (2000A)',
        '22': 'Subscriber Level(2000B) ',
        '23': 'Patient Level(2000C)'}

prv_mapping_dict = {
            'AD': 'Admitting Provider',
            'AT': 'Attending Provider',
            'BI': 'Billing Provider',
            'CO': 'Consulting Provider',
            'CV': 'Covering Provider',
            'H':  'Referring Provider',
            'LA': 'Laboratory',
            'OT': 'Other Provider',
            'P1': 'Pharmacist',
            'PC': 'Primary Care Provider',
            'PE': 'Performing Provider',
            'RP': 'Residing Provider',
            'SB': 'Submitting Provider',
            'SU': 'Supervising Provider'}

sbr_payer_resp_seq = {
     'P':'Primary',
     'S':'Secondary',
     'T':'Tertiary'}


sbr_mapping_dict = {
        '11': 'Other Non-Federal Programs',
        '12': 'Preferred Provider Organization (PPO)',
        '13':'Point of Service (POS)',
        '14':'Exclusive Provider Organization (EPO)',
        '15':'Indemnity Insurance',
        '16':'Health Maintenance Organization (HMO) Medicare Risk',
        '17':'Dental Maintenance Organization',
        'AM':'Automobile Medical',
        'CI': 'Commercial Insurance',
        'MA': 'Medicare Part A',
        'MB': 'Medicare Part B',
        'MC': 'Medicaid',
        'CH': 'Champus military health program',
        'VA': 'Veterans Affairs Plan',
        'OF': 'Other Federal Program',
        'WC': 'Workers Compensation',
        'LI': 'Liability Insurance',
        'BL': 'BCBS Insurance',
        'FI': 'Federal Employees Program',
        'HM': 'Health Maintenance Organization',
        'OF': 'Other Federal Program',
        'TV': 'Title V (Maternal and Child Health program)',
        'ZZ': 'Mutually Defined'}

clm_dtp_qualifier_mapping_dict = {
"434": "Statement Dates",
"435" : "Admission Date",
"096" : "Discharge Date",
"050" : "Repricer Receipt Date",
"051" : "Service Approval Date",
"232" : "Claim Statement Period Start",
"233" : "Claim Statement Period End",
"036" : "Date of Birth",
"439" : "Accident Date",
"484" : "Last Menstrual Period",
"454" : "Initial Treatment Date",
"472" : "Service Date",
"473" : "Prescription Date",
"573" : "Claim Paid Date",
"439" : "Accident Date",
"050" : "Repricer Receipt Date",
"431" : "Onset of Symptoms Illness"}


cl1_AdmissionTypeCode_mapping_dict = {
"1": "Emergency",
"2" : "Urgent",
"3" : "Elective",
"4" : "Newborn",
"5" : "Trauma",
"9" : "Information Not Available"}


cl1_AdmissionSourceCode_mapping_dict = {
"1": "Physician Referral",
"2" : "Clinic Referral",
"3" : "HMO Referral",
"4" : "Transfer from Hospital",
"5" : "Transfer from Skilled Nursing Facility",
"6" : "Transfer from other Health Care Facility",
"7" : "Emergency Room",
"8" : "Court Law Enforcement",
"9" : "HMO Referral",}

cl1_PatientStatusCode_mapping_dict = {
"01": "Discharged to Home or Self Care",
"02" : "Discharged/transferred to Short-term Hospital",
"03" : "Discharged/transferred to Skilled Nursing Facility",
"04" : "Discharged/transferred to Intermediate Care Facility",
"05" : "Discharged/transferred to another facility",
"20" : "Expired",
"30" : "Still Patient"}



clm_ref_dict = {
"D9" : "Claim Identifier Clearinghouse tracking number",
"EA" : "Medical Record Number",
"EI" : "Employer's Identification Number",
"F8" : "Resubmission Original Reference Number",
"9A" : "Repriced Claim Reference Number",
"9C" : "Adjusted Repriced Claim Reference Number",
"XZ" : "Pharmacy Prescription Number",
"1K" : "Payers Claim Number",
"LU" : "Location Number",
"4N" : "Special Payment Reference Number",
"P4" : "Project Code",
"LX" : "Qualified Products List",
"G4" : "Peer Review Organization (PRO) Approval Number",
"T4" : "CLIA Number",
"1A" : "Blue Cross Provider Number",
"1B" : "Blue Shield Provider Number",
"G1" : "Prior Authorization Number",
"9B" : "Referral Number",
"9F" : "Referral Number",
"REF01" : "Indicates type of reference",
"REF02" : "The actual reference number value"}

health_care_code_map_dict = {
    "ABK" : "Principal Diagnosis",
    "ABJ" : "Principal Diagnosis",
    "ABF" : "Other Diagnoses",
    "APR" : "Reason for Visit",
    "ABN" : "Reason for Visit",
    "BBR" : "Admitting Diagnosis",
    "BBQ" : "Discharge Diagnosis",
    "BR" : "Principal Procedure",
    "BP" : "External Cause of Injury",
    "BF" : "Condition Information",
    "BG" : "Diagnosis Related Group(DRG)",
    "DR" : "Diagnosis Related Group(DRG)",
    "BJ" : "NUBC Occurrence Codes",
    "BE" : "Value Information",
    "BH" : "NUBC Occurrence Span Codes",
    "BK" : "NUBC Treatment Codes",
    "BT" : "NUBC Condition Codes",
    "B1" : "NUBC Principal Procedure",
    "B2" : "Other Procedures",
    "B3" : "NUBC Principal Diagnosis",
    "B4" : "External Cause of Injury",
    "BF1" : "Occurrence Codes",
    "BF2" : "Value Codes",
    "BF3" : "Condition Codes"}



nm1_entityidentifiercode_map_dict = {
"71" : "Attending Physician",
"72" : "Operating Physician",
"ZZ" : "Other Operating Physician",
"82" : "Rendering Provider",
"77" : "Service Location",
"DN" : "Referring Provider",
"DQ": "Supervising Provider",           # Occasionally used in 837P/837I
"P3": "Primary Care Provider",          # Less common; may appear in some payer configs
"FA": "Facility",                       # Rare but can appear when separate from service location
"OB": "Ordered By"}


id_codequalifier_map_dict = {
"XX" : "NPI"}

"""# Begin Extracting Data from Segments

# 2300 Claim Segment
"""

def extract_2300_claim_elements():
    segment_id = 'CLM'

    clm_segment = get_segment(segment_id)
    count_clm = count_segmnt_pass_segmentid(segment_id)
    print(count_clm)
    #print(clm_segment)

    clm_rows = []
    clm_df = pd.DataFrame()

    for clm_segment in clm_segment:
        if clm_segment and len(clm_segment) >= 10:
            clm_data = { "clm_PatientControlNumber": clm_segment[1],
                "clm_TotalClaimChargeAmount": clm_segment[2],
                "clm_HealthCareServiceLocationInfo": clm_segment[5],
                "clm_AssignmentOrPlanParticipationCode": clm_segment[7],
                "clm_BenefitsAssignmentCertificationIndicator": clm_segment[8],
                "clm_ReleaseOfInformationCode": clm_segment[9]}
            clm_rows.append(clm_data)
        else:
            clm_df = error_message_segmentid(clm_df,segment_id)

    if clm_rows:
        clm_df = pd.DataFrame(clm_rows)
        clm_df = insert_additional_cols_df(clm_df, count_clm)
        clm_df[['clm_FacilityTypeCode', 'clm_FacilityCodeQualifier', 'clm_ClaimFrequencyTypeCode']] = \
        clm_df['clm_HealthCareServiceLocationInfo'].str.split('>', expand=True)


        clm_df['clm_FacilityTypeCodeDesc'] = clm_df['clm_FacilityTypeCode'].map(facilitytypecode_mapping_dict)
        clm_df['clm_FacilityCodeQualifierDesc'] = clm_df['clm_FacilityCodeQualifier'].map\
                                            (facilitycodequalifier_mapping_dict)
        clm_df['clm_ClaimFrequencyTypeCodeDesc'] = clm_df['clm_ClaimFrequencyTypeCode'].map\
                                                (frequencytypecode_mapping_dict)
        clm_df['clm_AssignmentOrPlanParticipationCodeDesc'] = clm_df['clm_AssignmentOrPlanParticipationCode'].\
                                                map(planparticipationCode_mapping_dict)



        clm_df = clm_df[['seg_count', 'file_name', 'clm_PatientControlNumber', 'clm_TotalClaimChargeAmount',\
            'clm_HealthCareServiceLocationInfo', 'clm_FacilityTypeCode', 'clm_FacilityTypeCodeDesc', \
            'clm_FacilityCodeQualifier',   'clm_FacilityCodeQualifierDesc',\
            'clm_ClaimFrequencyTypeCode','clm_ClaimFrequencyTypeCodeDesc',\
            'clm_AssignmentOrPlanParticipationCode', 'clm_AssignmentOrPlanParticipationCodeDesc',\
        'clm_BenefitsAssignmentCertificationIndicator', 'clm_ReleaseOfInformationCode']]

    else:
        clm_df = error_message_segmentid(clm_df,segment_id)

    return clm_df

clm_df  = extract_2300_claim_elements()
clm_df

"""# 2300 Claim Segment End

# 2400 Begin LX Claim Line
"""

def extract_2400_claim_lines():
    segment_id = 'LX'
    lx_segment, count_lx = get_segment_claimid(segment_id)

    print(count_lx)
    #print(nm1_pr_segment)


    lx_data = []
    lx_df = pd.DataFrame()

    for lx_seg in lx_segment:
        lx_elements = lx_seg[0]
        lx_claimid = lx_seg[1]

        if lx_elements and  len(lx_elements) >= 2:
            lx_data.append({ "clm_line_number": lx_elements[1], "claimid": lx_claimid})
        else:
            lx_df = error_message_segmentid(lx_df, "2400_"+ segment_id)


    if lx_data:
        lx_df = pd.DataFrame(lx_data)

        lx_df = insert_additional_cols_df(lx_df, count_lx)

        lx_df = lx_df[['seg_count', 'file_name', 'claimid', 'clm_line_number']]


    else:
        lx_df = error_message_segmentid(lx_df, "2400_"+ segment_id)

    return lx_df

lx_df = extract_2400_claim_lines()
lx_df

"""# End 2400 Begin LX Claim Line

# ISA Segment
"""

def extract_isa_segment():

    #edi = parse_edi_segments(folder_path)
    segment_id = 'ISA'
    count_isa = count_segmnt_pass_segmentid(segment_id)
    isa_segment = get_segment(segment_id)
    #print(count_isa)
    #print(isa_segment)

    isa_df = pd.DataFrame()

    for isa_segment in isa_segment:
        #print(isa_segment)
        if isa_segment and len(isa_segment) >= 17:  # Ensure ISA segment exists and has the required number of elements
            isa_data = {
                    "ISA_AuthorizationInformationQualifier_1": [isa_segment[1]],
                    "ISA_AuthorizationInformation_2": [isa_segment[2]],
                    "ISA_SecurityInformationQualifier_3": [isa_segment[3]],
                    "ISA_SecurityInformation_4": [isa_segment[4]],
                    "ISA_SenderIDQualifier_5": [isa_segment[5]],
                    "ISA_InterchangeSenderID_6": [isa_segment[6]],
                    "ISA_ReceiverIDQualifier_7": [isa_segment[7]],
                    "ISA_InterchangeReceiverID_8": [isa_segment[8]],
                    "ISA_InterchangeDate_9": [isa_segment[9]],
                    "ISA_InterchangeTime_10": [isa_segment[10]],
                    "ISA_InterchangeControlStandardsIdentifier_11": [isa_segment[11]],
                    "ISA_InterchangeControlVersionNumber_12": [isa_segment[12]],
                    "ISA_InterchangeControlNumber_13": [isa_segment[13]],
                    "ISA_AcknowledgementRequested_14": [isa_segment[14]],
                    "ISA_UsageIndicator_15": [isa_segment[15]],
                    "ISA_ComponentElementSeparator_16": [isa_segment[16]]}
            #print(isa_data)
            isa_df = pd.DataFrame(isa_data)
            isa_df = insert_additional_cols_df(isa_df, count_isa)
            #isa_df.insert(0, 'file_name', filename)
            #isa_df.insert(0, 'seg_count', count_isa)

        else:
            isa_df = error_message_segmentid(isa_df, segment_id)

    return isa_df

isa_df = extract_isa_segment()
isa_df

"""# GS Segment"""

def extract_gs_segment():

    segment_id = 'GS'
    gs_segment = get_segment(segment_id)
    count_gs = count_segmnt_pass_segmentid(segment_id)
    #print(count_gs)
    #print(gs_segment)
    gs_df = pd.DataFrame()


    for gs_segment in gs_segment :
        if gs_segment and len(gs_segment) >= 9:
            gs_data = {"GS_CodeIdentifyingInformationType_1": [gs_segment[1]],
                       "GS_SenderIDCode_2": [gs_segment[2]],
                       "GS_ReceiverIDCode_3": [gs_segment[3]],
                       "GS_Date_4": [gs_segment[4]],
                       "GS_Time_5": [gs_segment[5]],
                       "GS_GroupControlNumber_6": [gs_segment[6]],
                       "GS_TransactionTypeCode_7": [gs_segment[7]],
                       "GS_VersionAndRelease_8": [gs_segment[8]]}
            #print(isa_data)
            gs_df = pd.DataFrame(gs_data)
            gs_df = insert_additional_cols_df(gs_df, count_gs)
            #gs_df.insert(0, 'file_name', filename)
            #gs_df.insert(0, 'seg_count', count_gs)


        else:
            gs_df = error_message_segmentid(gs_df, segment_id)

    return gs_df

gs_df = extract_gs_segment()
gs_df

"""# ST Segment"""

def extract_st_segment():
    segment_id = 'ST'
    st_segment = get_segment(segment_id)
    count_st = count_segmnt_pass_segmentid(segment_id)
    #print(count_st)
    #print(st_segment)
    st_df = pd.DataFrame()


    for st_segment in st_segment:
        if st_segment and len(st_segment) >= 4:
            st_data = { "ST_TransactionSetIdentifierCode_01": [st_segment[1]],
                                    "ST_TransactionSetControlNumber_02": [st_segment[2]],
                                    "ST_ImplementationConventionPreference_03": [st_segment[3]]}
            #print(isa_data)
            st_df = pd.DataFrame(st_data)
            st_df = insert_additional_cols_df(st_df, count_st)
            #st_df.insert(0, 'file_name', filename)
            #st_df.insert(0, 'seg_count', count_st)

        else:
            st_df = error_message_segmentid(st_df, segment_id)
    return st_df

st_df = extract_st_segment()
st_df

"""# ST Segment"""

def extract_bht_segment():

    segment_id = 'BHT'
    bht_segment = get_segment(segment_id)
    count_bht = count_segmnt_pass_segmentid(segment_id)
    #print(count_bht)
    #print(bht_segment)
    bht_df = pd.DataFrame()

    for bht_segment in bht_segment:
        if bht_segment and len(bht_segment) >= 6:
            bht_data = { "BHT_HierarchicalStructureCode_01": [bht_segment[1]],
                                    "BHT_TransactionSetPurposeCode_02": [bht_segment[2]],
                                    "BHT_SubmitterTransactionIdentifier_03": [bht_segment[3]],
                                    "BHT_TransactionSetCreationDate_04": [bht_segment[4]],
                                    "BHT_TransactionSetCreationTime_05": [bht_segment[5]],
                                    "BHT_TransactionTypeCode_06": [bht_segment[6]]}
            #print(isa_data)
            bht_df = pd.DataFrame(bht_data)
            bht_df = insert_additional_cols_df(bht_df, count_bht)

        else:
            bht_df = error_message_segmentid(bht_df, segment_id)

    return bht_df

bht_df = extract_bht_segment()
bht_df

"""# 1000 A NM1 41 Segment"""

def extract_1000A_nm1_41_segment():

    segment_id = 'NM1'
    entity_id = '41'
    count_nm1_41 = count_segmnt_pass_segment_and_entity_id(segment_id, entity_id)
    nm1_41_segment = get_segment_entityid(segment_id,entity_id)
    #print(count_nm1_41)
    #print(any(isinstance(i, list) for i in nm1_41_segment))
    #flat = list(chain.from_iterable(nm1_41_segment))
    #print(nm1_41_segment)
    nm1_41_df = pd.DataFrame()

    if nm1_41_segment and len(nm1_41_segment) >= 10:
        nm1_41_data = { "NM1_41_EntityIdentifierCode_1": [nm1_41_segment[1]],
                "NM1_41_EntityTypeQualifier_2": [nm1_41_segment[2]],
                "NM1_41_NameLastOrOrganizationName_3": [nm1_41_segment[3]],
                "NM1_41_NameFirst_4": [nm1_41_segment[4]],
                "NM1_41_NameMiddle_5": [nm1_41_segment[5]],
                "NM1_41_NamePrefix_6": [nm1_41_segment[6]],
                "NM1_41_NameSuffix_7": [nm1_41_segment[7]],
                "NM1_41_IdentificationCodeQualifier_8": [nm1_41_segment[8]],
                "NM1_41_IdentificationCode_9": [nm1_41_segment[9]]}
        #print(isa_data)
        nm1_41_df = pd.DataFrame(nm1_41_data)
        nm1_41_df = insert_additional_cols_df(nm1_41_df, count_nm1_41)
    else:
        nm1_41_df = error_message_segmentid_entityid(nm1_41_df,segment_id, entity_id)
    return nm1_41_df

nm1_41_df = extract_1000A_nm1_41_segment()
nm1_41_df

"""# 2000A HL Billing Provider Hierarchical"""

def extract_2000A_HL_1_segment():
    segment_id = 'HL'
    entity_id = '1'
    count_hl_1 = count_segmnt_pass_segment_and_entity_id(segment_id, entity_id)
    hl_1_segment = get_segment_entityid(segment_id,entity_id)
    #print(count_hl_1)
    #print(hl_1_segment)
    hl_1_df = pd.DataFrame()
    if hl_1_segment and len(hl_1_segment) >= 4 :
        hl_1_data = { "hl_1_HierarchicalParentIDNumber": [hl_1_segment[1]],
                "hl_1_HierarchicalLevelCode": [hl_1_segment[3]],
                "hl_1_HierarchicalChildCode": [hl_1_segment[4]]}

        #print(isa_data)
        hl_1_df = pd.DataFrame(hl_1_data)
        hl_1_df = insert_additional_cols_df(hl_1_df, count_hl_1)
        hl_1_df['hl_1_HierarchicalLevelCodeDesc'] = hl_1_df['hl_1_HierarchicalLevelCode'].\
                                                        map(hl_mapping_dict)

    else:
        hl_1_df = error_message_segmentid_entityid(nm1_41_df,segment_id, entity_id)

    return hl_1_df

hl_1_df = extract_2000A_HL_1_segment()
hl_1_df

"""# 2000A PRV Billing Provider Specialty Information"""

def extract_2000A_PRV_BI_segment():
    segment_id = 'PRV'
    entity_id = 'BI'

    count_prv_bi = count_segmnt_pass_segment_and_entity_id(segment_id, entity_id)
    #print(count_prv_bi)

    prv_bi_segment = get_segment_entityid(segment_id,entity_id)
    #print(prv_bi_segment)

    prv_bi_df = pd.DataFrame()

    prv_bi_rows = []

    if prv_bi_segment:
        for prv_bi_data in prv_bi_segment:
            prv_bi_data = { "prv_bi_ProviderCode": prv_bi_data[1],
                "prv_bi_RIQ": prv_bi_data[2],
                "prv_bi_ProviderTaxonomyCode": prv_bi_data[3]}

            prv_bi_rows.append(prv_bi_data)

        prv_bi_df = pd.DataFrame(prv_bi_rows)
        prv_bi_df['prv_bi_ProviderCodeDesc'] = prv_bi_df['prv_bi_ProviderCode'].map(prv_mapping_dict)
        prv_bi_df = insert_additional_cols_df(prv_bi_df, count_prv_bi)
        prv_bi_df = prv_bi_df[['seg_count','file_name','prv_bi_ProviderCode','prv_bi_ProviderCodeDesc','prv_bi_RIQ',\
                           'prv_bi_ProviderTaxonomyCode']]


    else:
        prv_bi_df = error_message_segmentid_entityid(prv_bi_df,segment_id, entity_id)

    return prv_bi_df

prv_bi_df = extract_2000A_PRV_BI_segment()
prv_bi_df.drop_duplicates()
prv_bi_df

"""# 2010AA NM1 85 Billing Provider Name Loop"""

def extract_2010AA_NM1_85_segment():
    segment_id = 'NM1'
    entity_id = '85'

    count_nm1_85 = count_segmnt_pass_segment_and_entity_id(segment_id, entity_id)
    #print(count_nm1_85)

    nm1_85_segment = get_segment_entityid(segment_id,entity_id)
    #print(nm1_85_segment)

    nm1_85_rows = []
    nm1_85_df = pd.DataFrame()

    if nm1_85_segment:# and len(nm1_85_segment) >= 10:
        for nm1_85_data in nm1_85_segment:
            #print(nm1_85_data)
            nm1_85_data = { "nm1_85_EntityTypeQualifier": nm1_85_data[2],
                "nm1_85_BillingProviderLastOrOrglName": nm1_85_data[3],
                "nm1_85_IdentificationCodeQualifier": nm1_85_data[8],
                "nm1_85_BillingProviderIdentifier": nm1_85_data[9]}
            nm1_85_rows.append(nm1_85_data)
        nm1_85_df = pd.DataFrame(nm1_85_rows)
        nm1_85_df = insert_additional_cols_df(nm1_85_df, count_nm1_85)

        #print(isa_data)

    else:
        nm1_85_df = error_message_segmentid_entityid(nm1_85_df,segment_id, entity_id)

    return nm1_85_df

nm1_85_df = extract_2010AA_NM1_85_segment()
nm1_85_df

"""# 2010AA NM1 85, N4 Billing Provider City, State, ZIP Code"""

def extract_2010AA_NM1_85_N4_segment():
    segment_id = 'NM1'
    entity_id = '85'
    sub_segment_id = "N4"

    nm1_85_n4_records , count_nm1_85_n4 = get_segment_entityid_address(segment_id, entity_id, sub_segment_id)

    #print(nm1_85_n4_records)
    #print(count_nm1_85_n4)

    nm1_85_n4_cols = ["nm1_85_n4_City", "nm1_85_n4_State", "nm1_85_n4_PostalCode"]

    nm1_85_n4_df = pd.DataFrame(nm1_85_n4_records, columns=nm1_85_n4_cols)
    nm1_85_n4_df = insert_additional_cols_df(nm1_85_n4_df, count_nm1_85_n4)
    return nm1_85_n4_df

nm1_85_n4_df = extract_2010AA_NM1_85_N4_segment()
nm1_85_n4_df

"""# 2000B HL Segment to identify Subscriber level, Patient Level, Billing Provider"""

def extract_all_HL_segment():

    segment_id = 'HL'
    #entity_id = '2'
    hl_2_data = []
    hl_2_df = pd.DataFrame()

    #count_hl_2 = count_segmnt_pass_segmentid(segment_id)
    hl_2_segment, count_hl_2 = get_segment_claimid(segment_id)
    #print(count_hl_2)

    #print(hl_2_segment)
    for hl_2_seg in hl_2_segment:
        hl_2_elements = hl_2_seg[0]
        hl_2_claimid = hl_2_seg[1]
        if hl_2_seg:
            hl_2_data.append({ "hl_2_SBR_HierarchicalParentIDNumber": hl_2_elements[1],
                "hl_2_SBR_HierarchicalLevelCode": hl_2_elements[2],
                "hl_2_SBR_HierarchicalChildCode":hl_2_elements[3],
                 "claimid": hl_2_claimid})
        else:
            hl_2_df = error_message_segmentid(hl_2_df,segment_id)


    if hl_2_data:
        hl_2_df = pd.DataFrame(hl_2_data)
        hl_2_df = insert_additional_cols_df(hl_2_df, count_hl_2)
        hl_2_df['hl_2_SBR_HierarchicalChildCodeDesc'] = hl_2_df['hl_2_SBR_HierarchicalChildCode'].map(hl_mapping_dict)
        hl_2_df = hl_2_df[['seg_count', 'file_name', 'claimid', 'hl_2_SBR_HierarchicalParentIDNumber',\
                         'hl_2_SBR_HierarchicalLevelCode',\
                       'hl_2_SBR_HierarchicalChildCode', 'hl_2_SBR_HierarchicalChildCodeDesc']]

    else:
        hl_2_df = error_message_segmentid(hl_2_df,segment_id)

    return hl_2_df

hl_2_df= extract_all_HL_segment()
hl_2_df

hl_2_df.groupby('hl_2_SBR_HierarchicalChildCodeDesc').size()

#Subscriber Level Records

hl_2_22_sbr_df = hl_2_df[hl_2_df['hl_2_SBR_HierarchicalChildCode']== '22']

hl_2_22_sbr_df = hl_2_22_sbr_df.rename(columns={'hl_2_SBR_HierarchicalParentIDNumber': 'hl_2_22_SBR_ParentIDNumber',\
                                                'hl_2_SBR_HierarchicalLevelCode': 'hl_2_22_SBR_LevelCode',\
                                               'hl_2_SBR_HierarchicalChildCode': 'hl_2_22_SBR_ChildCode',\
                                              'hl_2_SBR_HierarchicalChildCodeDesc': 'hl_2_22_SBR_ChildCodeDesc'})


hl_2_22_sbr_df
#hl_2_df_sbr_lvl = hl_2_df_sbr_lvl.sort_values(by = 'claimid')

#Billing Provider Level Records
hl_2_20_bill_prv_df = hl_2_df[hl_2_df['hl_2_SBR_HierarchicalChildCode']== '20']

hl_2_20_bill_prv_df = hl_2_20_bill_prv_df.rename(columns={'hl_2_SBR_HierarchicalParentIDNumber': 'hl_2_20_Bill_Prv_ParentIDNumber',\
                                                'hl_2_SBR_HierarchicalLevelCode': 'hl_2_20_Bill_Prv_LevelCode',\
                                               'hl_2_SBR_HierarchicalChildCode': 'hl_2_20_Bill_Prv_ChildCode',\
                                              'hl_2_SBR_HierarchicalChildCodeDesc': 'hl_2_20_Bill_Prv_ChildCodeDesc'})



hl_2_20_bill_prv_df
#len(hl_2_20_bill_prv_df)

#Patient Level Records

hl_2_23_pat_df = hl_2_df[hl_2_df['hl_2_SBR_HierarchicalChildCode']== '23']

hl_2_23_pat_df = hl_2_23_pat_df.rename(columns={'hl_2_SBR_HierarchicalParentIDNumber': 'hl_2_23_PAT_ParentIDNumber',\
                                                'hl_2_SBR_HierarchicalLevelCode': 'hl_2_23_PAT_LevelCode',\
                                               'hl_2_SBR_HierarchicalChildCode': 'hl_2_23_PAT_ChildCode',\
                                              'hl_2_SBR_HierarchicalChildCodeDesc': 'hl_2_23_PAT_ChildCodeDesc'})


hl_2_23_pat_df

"""# End HL Segment to identify Subscriber level, Patient Level, Billing Provider

# 2000B Sbr P segment, Subscriber Segment to identify members Primary Coverage
"""

def extract_2000B_SBR_P_n_NM1_PR_segment():
    segmentid = "SBR"
    entityid = "P"
    rltd_segmentid = "NM1"
    rltd_entityid = "PR"

    sbr_p_segment, count_sbr_p = get_claimid_n_line_for_related_segmets(segmentid, \
                                                                        entityid,rltd_segmentid,rltd_entityid)
    #sbr_p_segment, count_sbr_p = get_segment_entity_id_claimid(segment_id,entity_id )
    print(count_sbr_p)
    #print(sbr_p_segment)

    sbr_p_data = []
    sbr_p_df = pd.DataFrame()

    for sbrp_nm1_pr_seg in sbr_p_segment:
            sbr_p_elements = sbrp_nm1_pr_seg[0]
            nm1_pr_elements = sbrp_nm1_pr_seg[1]
            sbrp_nm1_pr_claiminfo = sbrp_nm1_pr_seg[2]
            sbrp_nm1_pr_claimid = sbrp_nm1_pr_claiminfo[0]
            sbrp_nm1_pr_claimline = sbrp_nm1_pr_claiminfo[1]
            if (sbr_p_elements) and nm1_pr_elements and len(sbr_p_elements) >= 9 and len(nm1_pr_elements) >= 10:
                #print(nm1_pr_elements)
                sbr_p_data.append({ "sbr_p_PayerResponsibilitySequenceNumberCode": sbr_p_elements[1],
                    "sbr_p_IndividualRelationshipCode": sbr_p_elements[2],
                   "sbr_p_ClaimFilingIndicatorCode": sbr_p_elements[9],
                   "nm1_pr_PayerName": nm1_pr_elements[3],
                   "nm1_pr_PayerIdentificationCodeQualifier": nm1_pr_elements[8],
                   "nm1_pr_PayerIdentifier": nm1_pr_elements[9],
                   "claimid": sbrp_nm1_pr_claimid, "clm_line_number": sbrp_nm1_pr_claimline})
            else:
                sbr_p_df = error_message_segmentid_entityid(sbr_p_df,segment_id, entity_id)

            if sbr_p_data:
                sbr_p_df = pd.DataFrame(sbr_p_data)
                sbr_p_df = insert_additional_cols_df(sbr_p_df, count_sbr_p)
                sbr_p_df['sbr_p_PayerResponsibilitySequenceNumberCodeDesc'] = sbr_p_df['sbr_p_PayerResponsibilitySequenceNumberCode'].map(sbr_payer_resp_seq)
                sbr_p_df['sbr_p_ClaimFilingIndicatorCodeDesc'] = sbr_p_df['sbr_p_ClaimFilingIndicatorCode'].map(sbr_mapping_dict)
                sbr_p_df = sbr_p_df[['seg_count', 'file_name', 'claimid', 'sbr_p_PayerResponsibilitySequenceNumberCode',\
                                     'sbr_p_PayerResponsibilitySequenceNumberCodeDesc',\
                                   'sbr_p_IndividualRelationshipCode', 'sbr_p_ClaimFilingIndicatorCode',\
                                     'sbr_p_ClaimFilingIndicatorCodeDesc','nm1_pr_PayerName',\
                             'nm1_pr_PayerIdentificationCodeQualifier',\
                           'nm1_pr_PayerIdentifier']]
            else:
                sbr_p_df = error_message_segmentid_entityid(sbr_p_df,segment_id, entity_id)

    return sbr_p_df

sbr_p_df = extract_2000B_SBR_P_n_NM1_PR_segment()
sbr_p_df

"""# 2000B Sbr P segment, Subscriber Segment to identify members Secondary Coverage"""

def extract_2000B_SBR_S_n_NM1_PR_segment():
    segmentid = "SBR"
    entityid = "S"
    rltd_segmentid = "NM1"
    rltd_entityid = "PR"

    sbr_s_segment, count_sbr_s = get_claimid_n_line_for_related_segmets(segmentid, \
                                                                        entityid,rltd_segmentid,rltd_entityid)

    print(count_sbr_s)


    sbr_s_data = []
    sbr_s_df = pd.DataFrame()

    for sbrs_nm1_pr_seg in sbr_s_segment:
            sbr_s_elements = sbrs_nm1_pr_seg[0]
            nm1_pr_elements = sbrs_nm1_pr_seg[1]
            sbrs_nm1_pr_claiminfo = sbrs_nm1_pr_seg[2]
            sbrs_nm1_pr_claimid = sbrs_nm1_pr_claiminfo[0]
            sbrs_nm1_pr_claimline = sbrs_nm1_pr_claiminfo[1]
            if (sbr_s_elements) and nm1_pr_elements and len(sbr_s_elements) >= 9 and len(nm1_pr_elements) >= 10:
                #print(nm1_pr_elements)
                sbr_s_data.append({ "sbr_s_PayerResponsibilitySequenceNumberCode": sbr_s_elements[1],
                    "sbr_s_IndividualRelationshipCode": sbr_s_elements[2],
                   "sbr_s_ClaimFilingIndicatorCode": sbr_s_elements[9],
                   "nm1_pr_PayerName": nm1_pr_elements[3],
                   "nm1_pr_PayerIdentificationCodeQualifier": nm1_pr_elements[8],
                   "nm1_pr_PayerIdentifier": nm1_pr_elements[9],
                   "claimid": sbrs_nm1_pr_claimid, "clm_line_number": sbrs_nm1_pr_claimline})
            else:
                sbr_s_df = error_message_segmentid_entityid(sbr_s_df,segment_id, entity_id)

            if sbr_s_data:
                sbr_s_df = pd.DataFrame(sbr_s_data)
                sbr_s_df = insert_additional_cols_df(sbr_s_df, count_sbr_s)
                sbr_s_df['sbr_s_PayerResponsibilitySequenceNumberCodeDesc'] = sbr_s_df['sbr_s_PayerResponsibilitySequenceNumberCode'].map(sbr_payer_resp_seq)
                sbr_s_df['sbr_s_ClaimFilingIndicatorCodeDesc'] = sbr_s_df['sbr_s_ClaimFilingIndicatorCode'].map(sbr_mapping_dict)
                sbr_s_df = sbr_s_df[['seg_count', 'file_name', 'claimid', 'sbr_s_PayerResponsibilitySequenceNumberCode',\
                                     'sbr_s_PayerResponsibilitySequenceNumberCodeDesc',\
                                   'sbr_s_IndividualRelationshipCode', 'sbr_s_ClaimFilingIndicatorCode',\
                                     'sbr_s_ClaimFilingIndicatorCodeDesc','nm1_pr_PayerName',\
                             'nm1_pr_PayerIdentificationCodeQualifier',\
                           'nm1_pr_PayerIdentifier']]
            else:
                sbr_s_df = error_message_segmentid_entityid(sbr_s_df,segment_id, entity_id)

    return sbr_s_df

sbr_s_df = extract_2000B_SBR_S_n_NM1_PR_segment()
sbr_s_df

"""# 2000B Sbr P segment, Subscriber Segment to identify members Tertiary Coverage"""

def extract_2000B_SBR_T_n_NM1_PR_segment():
    segmentid = "SBR"
    entityid = "T"
    rltd_segmentid = "NM1"
    rltd_entityid = "PR"

    sbr_t_segment, count_sbr_t = get_claimid_n_line_for_related_segmets(segmentid, \
                                                                        entityid,rltd_segmentid,rltd_entityid)

    print(count_sbr_t)


    sbr_t_data = []
    sbr_t_df = pd.DataFrame()

    for sbrt_nm1_pr_seg in sbr_t_segment:
            sbr_t_elements = sbrt_nm1_pr_seg[0]
            nm1_pr_elements = sbrt_nm1_pr_seg[1]
            sbrt_nm1_pr_claiminfo = sbrt_nm1_pr_seg[2]
            sbrt_nm1_pr_claimid = sbrt_nm1_pr_claiminfo[0]
            sbrt_nm1_pr_claimline = sbrt_nm1_pr_claiminfo[1]
            if (sbr_t_elements) and nm1_pr_elements and len(sbr_t_elements) >= 9 and len(nm1_pr_elements) >= 10:
                #print(nm1_pr_elements)
                sbr_t_data.append({ "sbr_t_PayerResponsibilitySequenceNumberCode": sbr_t_elements[1],
                    "sbr_t_IndividualRelationshipCode": sbr_t_elements[2],
                   "sbr_t_ClaimFilingIndicatorCode": sbr_t_elements[9],
                   "nm1_pr_PayerName": nm1_pr_elements[3],
                   "nm1_pr_PayerIdentificationCodeQualifier": nm1_pr_elements[8],
                   "nm1_pr_PayerIdentifier": nm1_pr_elements[9],
                   "claimid": sbrt_nm1_pr_claimid, "clm_line_number": sbrt_nm1_pr_claimline})
            else:
                sbr_t_df = error_message_segmentid_entityid(sbr_t_df,segment_id, entity_id)

            if sbr_t_data:
                sbr_t_df = pd.DataFrame(sbr_t_data)
                sbr_t_df = insert_additional_cols_df(sbr_t_df, count_sbr_t)
                sbr_t_df['sbr_t_PayerResponsibilitySequenceNumberCodeDesc'] = sbr_t_df['sbr_t_PayerResponsibilitySequenceNumberCode'].map(sbr_payer_resp_seq)
                sbr_t_df['sbr_t_ClaimFilingIndicatorCodeDesc'] = sbr_t_df['sbr_t_ClaimFilingIndicatorCode'].map(sbr_mapping_dict)
                sbr_t_df = sbr_t_df[['seg_count', 'file_name', 'claimid', 'sbr_t_PayerResponsibilitySequenceNumberCode',\
                                     'sbr_t_PayerResponsibilitySequenceNumberCodeDesc',\
                                   'sbr_t_IndividualRelationshipCode', 'sbr_t_ClaimFilingIndicatorCode',\
                                     'sbr_t_ClaimFilingIndicatorCodeDesc','nm1_pr_PayerName',\
                             'nm1_pr_PayerIdentificationCodeQualifier',\
                           'nm1_pr_PayerIdentifier']]
            else:
                sbr_t_df = error_message_segmentid_entityid(sbr_t_df,segment_id, entity_id)

    return sbr_t_df

sbr_t_df = extract_2000B_SBR_T_n_NM1_PR_segment()
sbr_t_df

"""# End Sbr P segment, Subscriber Segment to identify members Primary or Secondary Coverage

# 2300 DTP Elements between CLM and LX
"""

def extract_2300_clm_dtp_segment():

    begin_segmentid = 'CLM'
    end_segmentid = 'LX'
    req_segmentid = 'DTP'

    #clm_dtp_segment, count_clm_dtp = get_subsequent_segment(segment_id, subsequent_seg_id)
    clm_dtp_segment, count_clm_dtp = get_segs_btwn_2_segs_claim_block(begin_segmentid, end_segmentid, req_segmentid)
    #print(count_clm_dtp)
    #print(clm_dtp_segment)

    clm_dtp_data = []
    clm_dtp_df = pd.DataFrame()

    for clm_dtp_seg in clm_dtp_segment:
        clm_dtp_elements = clm_dtp_seg[0]
        clm_dtp_claimid = clm_dtp_seg[1]
        if clm_dtp_elements and  len(clm_dtp_elements) >= 4:
            clm_dtp_data.append({ "clm_dtp_DateTimeQualifier": clm_dtp_elements[1],
                "clm_dtp_DateTimePeriodFormatQualifier": clm_dtp_elements[2],
               "clm_dtp_DateofService": clm_dtp_elements[3], "claimid": clm_dtp_claimid})
        else:
            clm_dtp_df = error_message_segmentid_entityid(clm_dtp_df,begin_segmentid, req_segmentid)

    if clm_dtp_data:
        clm_dtp_df = pd.DataFrame(clm_dtp_data)
        clm_dtp_df = insert_additional_cols_df(clm_dtp_df, count_clm_dtp)

        clm_dtp_df['clm_dtp_DateTimeQualifierDesc'] = clm_dtp_df['clm_dtp_DateTimeQualifier'].map(clm_dtp_qualifier_mapping_dict)

        clm_dtp_df = clm_dtp_df[['seg_count', 'file_name', 'claimid', 'clm_dtp_DateTimeQualifier',\
                             'clm_dtp_DateTimeQualifierDesc',\
                           'clm_dtp_DateTimePeriodFormatQualifier', 'clm_dtp_DateofService']]
    else:
        clm_dtp_df = error_message_segmentid_entityid(clm_dtp_df,begin_segmentid, req_segmentid)

    return clm_dtp_df

clm_dtp_df = extract_2300_clm_dtp_segment()
clm_dtp_df.groupby('clm_dtp_DateTimeQualifierDesc').size()

clm_dtp_df

#Claim DTP Statement Dates
clm_dtp_statement_dates_df = clm_dtp_df[clm_dtp_df['clm_dtp_DateTimeQualifier']== '434']

#Claim DTP Admission Dates
clm_dtp_admission_dates_df = clm_dtp_df[clm_dtp_df['clm_dtp_DateTimeQualifier']== '435']
#hl_2_df_sbr_lvl = hl_2_df_sbr_lvl.sort_values(by = 'claimid')

#Claim DTP Discharge Dates
clm_dtp_discharge_dates_df = clm_dtp_df[clm_dtp_df['clm_dtp_DateTimeQualifier']== '096']
#hl_2_df_sbr_lvl = hl_2_df_sbr_lvl.sort_values(by = 'claimid')

#Claim DTP Claim Paid Dates
clm_dtp_claim_paid_dates_df = clm_dtp_df[clm_dtp_df['clm_dtp_DateTimeQualifier']== '573']
#hl_2_df_sbr_lvl = hl_2_df_sbr_lvl.sort_values(by = 'claimid')

"""# End DTP Elements between CLM and LX

# CL1 Segment
"""

def extract_2300_clm_cl1_segment():

    segment_id = 'CL1'

    #clm_dtp_segment, count_clm_dtp = get_subsequent_segment(segment_id, subsequent_seg_id)
    cl1_segment, count_cl1 = get_segment_claimid(segment_id)
    #print(count_cl1)
    #print(cl1_segment)

    cl1_data = []
    cl1_df = pd.DataFrame()

    for cl1_seg in cl1_segment:
        cl1_elements = cl1_seg[0]
        cl1_claimid = cl1_seg[1]
        if cl1_elements and  len(cl1_elements) >= 4:
            cl1_data.append({ "cl1_AdmissionTypeCode": cl1_elements[1],
                "cl1_AdmissionSourceCode": cl1_elements[2],
               "cl1_PatientStatusCode": cl1_elements[3], "claimid": cl1_claimid})
        else:
            cl1_df = error_message_segmentid(cl1_df,segment_id)

    if cl1_data:
        cl1_df = pd.DataFrame(cl1_data)
        cl1_df = insert_additional_cols_df(cl1_df, count_cl1)

        cl1_df['cl1_AdmissionTypeCodeDesc'] = cl1_df['cl1_AdmissionTypeCode'].map(cl1_AdmissionTypeCode_mapping_dict)
        cl1_df['cl1_AdmissionSourceCodeDesc'] = cl1_df['cl1_AdmissionSourceCode'].\
                                                                    map(cl1_AdmissionSourceCode_mapping_dict)
        cl1_df['cl1_PatientStatusCodeDesc'] = cl1_df['cl1_PatientStatusCode'].map(cl1_PatientStatusCode_mapping_dict)

        cl1_df = cl1_df[['seg_count', 'file_name', 'claimid', 'cl1_AdmissionTypeCode',\
                         'cl1_AdmissionTypeCodeDesc','cl1_AdmissionSourceCode','cl1_AdmissionSourceCodeDesc', \
                       'cl1_PatientStatusCode', 'cl1_PatientStatusCodeDesc']]
    else:
        cl1_df = error_message_segmentid(cl1_df,segment_id)

    return cl1_df

cl1_df = extract_2300_clm_cl1_segment()
cl1_df

"""# End CL1 Segment

# 2300 CLM REF segments between CLM and LX
"""

def extract_2300_clm_ref_segment():

    begin_segmentid = 'CLM'
    end_segmentid = 'LX'
    req_segmentid = 'REF'


    #clm_dtp_segment, count_clm_dtp = get_subsequent_segment(segment_id, subsequent_seg_id)
    clm_ref_segment, count_clm_ref =  get_segs_btwn_2_segs_claim_block(begin_segmentid, end_segmentid, req_segmentid)
    #print(count_clm_ref)
    #print(clm_ref_segment)

    clm_ref_data = []
    clm_ref_df = pd.DataFrame()

    for clm_ref_seg in clm_ref_segment:
        clm_ref_elements = clm_ref_seg[0]
        clm_ref_claimid = clm_ref_seg[1]
        if clm_ref_elements:
            clm_ref_data.append({ "clm_ref_ReferenceIdentificationQualifier": clm_ref_elements[1],
                    "clm_ref_ReferenceIdentificationQualifierValue": clm_ref_elements[2],
                    "claimid": clm_ref_claimid})
        else:
            clm_ref_df = error_message_segmentid_entityid(clm_ref_df,begin_segmentid, req_segmentid)

    if clm_ref_data:
        clm_ref_df = pd.DataFrame(clm_ref_data)
        clm_ref_df = insert_additional_cols_df(clm_ref_df, count_clm_ref)
        clm_ref_df['clm_ref_ReferenceIdentificationQualifierDesc'] = clm_ref_df\
                                ['clm_ref_ReferenceIdentificationQualifier'].map(clm_ref_dict)
        clm_ref_df = clm_ref_df[['seg_count', 'file_name', 'claimid', 'clm_ref_ReferenceIdentificationQualifier',\
                             'clm_ref_ReferenceIdentificationQualifierDesc','clm_ref_ReferenceIdentificationQualifierValue']]
    else:
        clm_ref_df = error_message_segmentid_entityid(clm_ref_df,begin_segmentid, req_segmentid)

    return clm_ref_df

clm_ref_df = extract_2300_clm_ref_segment()
clm_ref_df.groupby('clm_ref_ReferenceIdentificationQualifierDesc').size()

clm_ref_df

#Claim REF Segments D9 ReferenceIdentificationQualifier
clm_ref_D9_df = clm_ref_df[clm_ref_df['clm_ref_ReferenceIdentificationQualifier']== 'D9']

clm_ref_D9_df

#Claim REF Segments EA ReferenceIdentificationQualifier
clm_ref_EA_df = clm_ref_df[clm_ref_df['clm_ref_ReferenceIdentificationQualifier']== 'EA']

#Claim REF Segments F8 ReferenceIdentificationQualifier
clm_ref_F8_df = clm_ref_df[clm_ref_df['clm_ref_ReferenceIdentificationQualifier']== 'F8']

#Claim REF Segments G1 ReferenceIdentificationQualifier
clm_ref_G1_df = clm_ref_df[clm_ref_df['clm_ref_ReferenceIdentificationQualifier']== 'G1']

"""# End CLM REF segments between CLM and LX

# CLM HI segments between CLM and LX
"""

def extract_2300_clm_hi_segment():
    begin_segmentid = 'CLM'
    end_segmentid = 'LX'
    req_segmentid = 'HI'

    clm_hi_segment, count_clm_hi =  get_segs_btwn_2_segs_claim_block(begin_segmentid, end_segmentid, req_segmentid)
    #print(count_clm_hi)


    clm_hi_data = []
    clm_hi_df = pd.DataFrame()


    for clm_hi_seg in clm_hi_segment:
        #print( clm_hi_segment)
        clm_hi_elements = clm_hi_seg[0]
        clm_hi_claimid = clm_hi_seg[1]
        if len(clm_hi_elements) >= 3:
            clm_hi_data.append({ "clm_hi_HealthCareCodeInformation1": clm_hi_elements[1],
                "clm_hi_HealthCareCodeInformation2": clm_hi_elements[2],
                "claimid": clm_hi_claimid})
        elif len(clm_hi_elements) == 2:
            clm_hi_data.append({ "clm_hi_HealthCareCodeInformation1": clm_hi_elements[1],
                "clm_hi_HealthCareCodeInformation2": None,
                "claimid": clm_hi_claimid})
        else:
            clm_hi_df = error_message_segmentid_entityid(clm_hi_df,begin_segmentid, req_segmentid)


    if clm_hi_data:
        clm_hi_df = pd.DataFrame(clm_hi_data)

        clm_hi_df = insert_additional_cols_df(clm_hi_df, count_clm_hi)

        clm_hi_df[['clm_hi_CodeListQualifierCode1', 'clm_CodeValue1']] = (clm_hi_df['clm_hi_HealthCareCodeInformation1']\
                                                                        .str.split('>', n=1,expand=True))

        clm_hi_df[['clm_hi_CodeListQualifierCode2', 'clm_CodeValue2']] = (clm_hi_df['clm_hi_HealthCareCodeInformation2']\
                                                                        .str.split('>', n=1,expand=True))

        clm_hi_df['clm_hi_CodeListQualifierCodeDesc1'] = clm_hi_df['clm_hi_CodeListQualifierCode1'].\
                                                            map(health_care_code_map_dict)
        clm_hi_df['clm_hi_CodeListQualifierCodeDesc2'] = clm_hi_df['clm_hi_CodeListQualifierCode2'].\
                                                            map(health_care_code_map_dict)

        clm_hi_df = clm_hi_df[['seg_count', 'file_name', 'claimid', 'clm_hi_HealthCareCodeInformation1',\
                               #'clm_hi_HealthCareCodeInformation2',\
                             'clm_hi_CodeListQualifierCode1','clm_hi_CodeListQualifierCodeDesc1','clm_CodeValue1',\
                              'clm_hi_CodeListQualifierCode2','clm_hi_CodeListQualifierCodeDesc2','clm_CodeValue2']]

    else:
        clm_hi_df = error_message_segmentid_entityid(clm_hi_df,begin_segmentid, req_segmentid)

    return clm_hi_df

clm_hi_df = extract_2300_clm_hi_segment()
clm_hi_df

clm_hi_df.groupby('clm_hi_CodeListQualifierCodeDesc1').size()

clm_hi_df.groupby('clm_hi_CodeListQualifierCodeDesc2').size()

clm_hi_df.groupby('clm_hi_CodeListQualifierCode1').size()

clm_hi_df.groupby('clm_hi_CodeListQualifierCodeDesc1').size()

"""# End CLM HI segments between CLM and LX

# CLM NM1  segments between CLM and LX
"""

def extract_2300_clm_nm1_provider_segment():

    begin_segmentid = 'CLM'
    end_segmentid = 'LX'
    req_segmentid = 'NM1'

    nm1_2310_segment, count_nm1_2310 = get_segs_btwn_2_segs_claim_block(begin_segmentid, end_segmentid, req_segmentid)

    nm1_2310_data = []
    nm1_2310_df = pd.DataFrame()

    for nm1_2310_seg in nm1_2310_segment:
        nm1_2310_elements = nm1_2310_seg[0]
        nm1_2310_claimid = nm1_2310_seg[1]
        if nm1_2310_elements and  len(nm1_2310_elements) >= 10:
            nm1_2310_data.append({ "nm1_2310_EntityIdentifierCode": nm1_2310_elements[1],
                "nm1_2310_IdentificationCodeQualifier": nm1_2310_elements[8],
               "nm1_2310_PrimaryIdentifier": nm1_2310_elements[9], "claimid": nm1_2310_claimid})
        else:
            nm1_2310_df = error_message_segmentid_entityid(nm1_2310_df, "2310_"+ begin_segmentid, req_segmentid)

    if nm1_2310_data:
        nm1_2310_df = pd.DataFrame(nm1_2310_data)

        nm1_2310_df = insert_additional_cols_df(nm1_2310_df, count_nm1_2310)

        nm1_2310_df['nm1_2310_IdentificationCodeQualifierDesc'] = nm1_2310_df\
                                    ['nm1_2310_IdentificationCodeQualifier'].map(id_codequalifier_map_dict)

        nm1_2310_df['nm1_2310_EntityIdentifierCodeDesc'] = nm1_2310_df\
                                ['nm1_2310_EntityIdentifierCode'].map(nm1_entityidentifiercode_map_dict)


        nm1_2310_df = nm1_2310_df[['seg_count', 'file_name', 'claimid', 'nm1_2310_EntityIdentifierCode',\
                             'nm1_2310_EntityIdentifierCodeDesc','nm1_2310_IdentificationCodeQualifier',
                                   'nm1_2310_IdentificationCodeQualifierDesc',\
                           'nm1_2310_PrimaryIdentifier']]

    else:
        nm1_2310_df = error_message_segmentid_entityid(nm1_2310_df, "2310_"+ begin_segmentid, req_segmentid)

    return nm1_2310_df

nm1_2310_df = extract_2300_clm_nm1_provider_segment()
nm1_2310_df.groupby('nm1_2310_EntityIdentifierCode').size()

nm1_2310_df

nm1_2310_df.groupby('nm1_2310_EntityIdentifierCodeDesc').size()

"""# CLM PRV segments between CLM and LX"""

begin_segmentid = 'CLM'
end_segmentid = 'LX'
req_segmentid = 'PRV'


clm_prv_providercode_map_dict = {
"AT" : "Attending Physician",
"OP" : "Operating Physician",
"OR" : "Other Operating Physician",
"PE" : "Performing Provider",
"RP" : "Referring Provider",
"P3" : "Primary Care Provider"}


clm_prv_ref_id_qualifier_map_dict = {
"PXC" : "Health Care Provider Taxonomy Code"}

clm_prv_segment, count_clm_prv = get_segs_btwn_2_segs_claim_block(begin_segmentid, end_segmentid, req_segmentid)

print(count_clm_prv)
#print(nm1_pr_segment)


clm_prv_data = []
clm_prv_df = pd.DataFrame()

for clm_prv_seg in clm_prv_segment:
    clm_prv_elements = clm_prv_seg[0]
    clm_prv_claimid = clm_prv_seg[1]
    if clm_prv_elements and  len(clm_prv_elements) >= 3:
        clm_prv_data.append({ "clm_prv_ProviderCode": clm_prv_elements[1],
            "clm_prv_ReferenceIdentificationQualifier": clm_prv_elements[2],
           "clm_prv_ProviderTaxonomyCode": clm_prv_elements[3], "claimid": clm_prv_claimid})
    else:
        clm_prv_df = error_message_segmentid_entityid(clm_prv_df, "2310_"+ begin_segmentid, req_segmentid)

if clm_prv_data:
    clm_prv_df = pd.DataFrame(clm_prv_data)

    clm_prv_df = insert_additional_cols_df(clm_prv_df, count_clm_prv)

    clm_prv_df['clm_prv_ProviderCodeDesc'] = clm_prv_df\
                                ['clm_prv_ProviderCode'].map(clm_prv_providercode_map_dict)

    clm_prv_df['clm_prv_ReferenceIdentificationQualifierDesc'] = clm_prv_df\
                            ['clm_prv_ReferenceIdentificationQualifier'].map(clm_prv_ref_id_qualifier_map_dict)
    clm_prv_df = clm_prv_df[['seg_count', 'file_name', 'claimid', 'clm_prv_ProviderCode',\
                         'clm_prv_ProviderCodeDesc','clm_prv_ReferenceIdentificationQualifier',
                               'clm_prv_ReferenceIdentificationQualifierDesc',\
                       'clm_prv_ProviderTaxonomyCode']]


else:
    clm_prv_df = error_message_segmentid_entityid(clm_prv_df, "2310_"+ begin_segmentid, req_segmentid)

clm_prv_df

"""# END CLM PRV segments between CLM and LX

# 2400 Claim Line SV2 Segment
"""

segment_id = 'SV2'

lx_sv2_serviceid_qualifiers_map_dict = {
"HC" : "HCPCS",
"HP" : "HIPPS Rate Codes (Home Health, SNF, etc.)",
"ID" : "Internal Drug Code used by payers or providers",
"IV" : "Home Infusion EDI Coalition (HIEC) codes",
"WK" : "DRG Code",
"ZZ" : "Mutually defined"}


lx_sv2_unit_measurement_code_map_dict = {
"DA" : "Days",
"UN" : "Unit"}


lx_sv2_segment, count_lx_sv2 = get_claimid_n_line_use_line_segmentid(segment_id)

print(count_lx_sv2)
#print(nm1_pr_segment)


lx_sv2_data = []
lx_sv2_df = pd.DataFrame()

for lx_sv2_seg in lx_sv2_segment:
    lx_sv2_elements = lx_sv2_seg[0]
    lx_sv2_claiminfo = lx_sv2_seg[1]
    lx_sv2_claim_id = lx_sv2_claiminfo[0]
    lx_sv2_claim_line = lx_sv2_claiminfo[1]

    if lx_sv2_elements and  len(lx_sv2_elements) >= 6:
        lx_sv2_data.append({ "lx_sv2_RevenueCode": lx_sv2_elements[1],
            "lx_sv2_MedicalProcedureIdentifier": lx_sv2_elements[2],
            "lx_sv2_LineItemChargeAmount": lx_sv2_elements[3],
            "lx_sv2_UnitBasisforMeasurementCode": lx_sv2_elements[4],
            "lx_sv2_ServiceUnitCount": lx_sv2_elements[5],
            "claimid": lx_sv2_claim_id,"clm_line_number": lx_sv2_claim_line})
    else:
        lx_sv2_df = error_message_segmentid(lx_sv2_data, "2400_"+ segment_id)


if lx_sv2_data:
    lx_sv2_df = pd.DataFrame(lx_sv2_data)

    lx_sv2_df = insert_additional_cols_df(lx_sv2_df, count_lx_sv2)

    lx_sv2_df[['lx_sv2_ProcedureIDQualifier', 'lx_sv2_ProcedureCode']] = (lx_sv2_df\
                                                                          ['lx_sv2_MedicalProcedureIdentifier'].str.split('>', n=1, expand=True))

    lx_sv2_df['lx_sv2_ProcedureIDQualifierDesc'] = lx_sv2_df['lx_sv2_ProcedureIDQualifier'].\
                                                        map(lx_sv2_serviceid_qualifiers_map_dict)

    lx_sv2_df[['lx_sv2_ProcedureCode', 'lx_sv2_ProcedureModifier']] = (lx_sv2_df['lx_sv2_ProcedureCode'].str\
                                                         .split('>', n=1, expand=True))

    lx_sv2_df['lx_sv2_UnitBasisforMeasurementCodeDesc'] = lx_sv2_df['lx_sv2_UnitBasisforMeasurementCode'].\
                                                        map(lx_sv2_unit_measurement_code_map_dict)



    lx_sv2_df = lx_sv2_df[['seg_count', 'file_name', 'claimid', 'clm_line_number', 'lx_sv2_RevenueCode',\
                         "lx_sv2_MedicalProcedureIdentifier","lx_sv2_ProcedureIDQualifier",'lx_sv2_ProcedureIDQualifierDesc',\
                           "lx_sv2_ProcedureCode",'lx_sv2_ProcedureModifier',\
                          "lx_sv2_LineItemChargeAmount",\
                           "lx_sv2_UnitBasisforMeasurementCode",'lx_sv2_UnitBasisforMeasurementCodeDesc',\
                        "lx_sv2_ServiceUnitCount"]]


else:
    lx_sv2_df = error_message_segmentid(lx_sv2_df, "2400_"+ segment_id)

lx_sv2_df

"""# 2400 SV2 DTP segment"""

begin_segmentid='SV2'
end_segmentid='CLM'
req_line_segmentid='DTP'

clm_line_sv2_dtp_qualifier_mapping_dict = {
"434": "Statement Dates",
"435" : "Admission Date",
"096" : "Discharge Date",
"050" : "Repricer Receipt Date",
"051" : "Service Approval Date",
"232" : "Claim Statement Period Start",
"233" : "Claim Statement Period End",
"036" : "Date of Birth",
"439" : "Accident Date",
"484" : "Last Menstrual Period",
"454" : "Initial Treatment Date",
"472" : "Service Date",
"473" : "Prescription Date",
"573" : "Claim Paid Date",
"439" : "Accident Date",
"050" : "Repricer Receipt Date",
"431" : "Onset of Symptoms Illness"}


clm_line_sv2_dtp_dt_time_qualfr_mapping_dict = {
"D8": "Format CCYYMMDD",
"RD8" : "Format CCYYMMDD-CCYYMMDD"}


lx_sv2_dtp_segment, count_lx_sv2_dtp = get_claimid_n_line_btwn_2_segs_claim_line_block(begin_segmentid,end_segmentid, req_line_segmentid)
print(count_lx_sv2_dtp)

lx_sv2_dtp_data = []
lx_sv2_dtp_df = pd.DataFrame()

for lx_sv2_dtp_seg in lx_sv2_dtp_segment:
    lx_sv2_dtp_elements = lx_sv2_dtp_seg[0]
    lx_sv2_dtp_claiminfo = lx_sv2_dtp_seg[1]
    lx_sv2_dtp_claim_id = lx_sv2_dtp_claiminfo[0]
    lx_sv2_dtp_claim_line = lx_sv2_dtp_claiminfo[1]

    if lx_sv2_dtp_elements and  len(lx_sv2_dtp_elements) >= 4:
        lx_sv2_dtp_data.append({ "lx_sv2_dtp_DateTimeQualifier": lx_sv2_dtp_elements[1],
            "lx_sv2_dtp_DateTimePeriodFormatQualifier": lx_sv2_dtp_elements[2],
            "lx_sv2_dtp_ServiceDate": lx_sv2_dtp_elements[3],
            "claimid": lx_sv2_dtp_claim_id,"clm_line_number": lx_sv2_dtp_claim_line})
    else:
        lx_sv2_dtp_df = error_message_segmentid(lx_sv2_dtp_data, "2400_"+ segment_id)


if lx_sv2_dtp_data:
    lx_sv2_dtp_df = pd.DataFrame(lx_sv2_dtp_data)

    lx_sv2_dtp_df = insert_additional_cols_df(lx_sv2_dtp_df, count_lx_sv2_dtp)


    lx_sv2_dtp_df['lx_sv2_dtp_DateTimeQualifierDesc'] = lx_sv2_dtp_df['lx_sv2_dtp_DateTimeQualifier'].\
                                                        map(clm_line_sv2_dtp_qualifier_mapping_dict)

    lx_sv2_dtp_df['lx_sv2_dtp_DateTimePeriodFormatQualifierDesc'] = lx_sv2_dtp_df['lx_sv2_dtp_DateTimePeriodFormatQualifier'].\
                                                        map(clm_line_sv2_dtp_dt_time_qualfr_mapping_dict)



    lx_sv2_dtp_df = lx_sv2_dtp_df[['seg_count', 'file_name', 'claimid', 'clm_line_number',\
                                 'lx_sv2_dtp_DateTimeQualifier','lx_sv2_dtp_DateTimeQualifierDesc',\
                                 'lx_sv2_dtp_DateTimePeriodFormatQualifier',\
                                   'lx_sv2_dtp_DateTimePeriodFormatQualifierDesc',\
                                   'lx_sv2_dtp_ServiceDate']]


else:
    lx_sv2_dtp_df = error_message_segmentid(lx_sv2_dtp_df, "2400_"+ segment_id)

lx_sv2_dtp_df

